import React from "react";
import { Metadata } from "next";
import "./globals.css";

import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { poppins } from "./fonts";
import { cn } from "../lib/utils";
import NavigationMobile from "../components/navigation-mobile";
import { PageIndicator } from "@/components/page-indicator";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className={cn(poppins.className)}>
        <Navbar />
        {children}
        <NavigationMobile />
        <PageIndicator />
        <Footer />
      </body>
    </html>
  );
}
